name: "jaffle_shop"

version: "1.0.0"

profile: "default"

clean-targets:
  - "dbt_packages"
  - "logs"
  - "target"

analysis-paths:
  - "analyses"

macro-paths:
  - "macros"

model-paths:
  - "models"

seed-paths:
  - "seeds"

snapshot-paths:
  - "snapshots"

test-paths:
  - "tests"

models:
  jaffle_shop:
    +materialized: "table"
