default:
  target: "default"
  outputs:
    default:
      type: "duckdb"
      path: "{{ env_var('SD_DATA_DIR') }}/default.db"
      threads: 4
sample:
  target: "default"
  outputs:
    default:
      type: "duckdb"
      path: "{{ env_var('SD_DATA_DIR') }}/sample.db"
      threads: 4
