name: "example"

version: "1.0.0"

profile: "example"

clean-targets:
  - "dbt_packages"
  - "target"

analysis-paths:
  - "analyses"

macro-paths:
  - "macros"

model-paths:
  - "models"

seed-paths:
  - "seeds"

snapshot-paths:
  - "snapshots"

test-paths:
  - "tests"

models:
  example:
    +materialized: view
